spring.application.name=TraineeAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/Capgemini
spring.datasource.username=postgres
spring.datasource.password=Superset@26
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8000