spring.application.name=MovieApp

spring.datasource.url=jdbc:postgresql://localhost:5432/Capgemini
spring.datasource.username=postgres
spring.datasource.password=Superset@26

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8085
